SELECT ID ,EMAIL ,PASSWORD ,NAME ,REGDATE FROM MEMBER;

DELETE FROM MEMBER;

SELECT ID ,EMAIL ,PASSWORD, NAME , REGDATE as RegisterDateTime FROM MEMBER

SELECT ID ,EMAIL ,PASSWORD ,NAME ,REGDATE 
  FROM MEMBER
 WHERE REGDATE BETWEEN '2020-09-01' AND '2020-09-30'
 ORDER BY REGDATE DESC;